Revert "Don't jump to high clocks for NVENC/NVDEC."
This reverts commit 908714aa10e2cbd216b1ccdea93c5e4635bb404d.

Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: failed to fulfil mount request: open /bin/nvidia-cuda-mps-control: no such file or directory